"""
modules/document_engine.py
Generate PDF and DOCX documents from content or auto-pulled data.
Deps: fpdf2, python-docx  (pip install fpdf2 python-docx)
"""

import os
import time
import threading

_OUTPUT_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "shared")


def _ensure_dir():
    os.makedirs(_OUTPUT_DIR, exist_ok=True)


def _timestamp() -> str:
    return time.strftime("%Y%m%d_%H%M%S")


# ── PDF ───────────────────────────────────────────────────────

def _latin1_safe(text: str) -> str:
    """Strip/replace chars outside Latin-1 so Helvetica doesn't crash."""
    return text.encode("latin-1", errors="replace").decode("latin-1")


def _make_pdf(title: str, body: str, filename: str) -> str:
    from fpdf import FPDF

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # Title
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(30, 30, 30)
    pdf.multi_cell(0, 10, _latin1_safe(title), align="C")
    pdf.ln(4)

    # Date line
    pdf.set_font("Helvetica", "I", 10)
    pdf.set_text_color(120, 120, 120)
    pdf.cell(0, 6, f"Generated by iZACH - {time.strftime('%d %b %Y, %H:%M')}", ln=True, align="C")
    pdf.ln(6)

    # Divider
    pdf.set_draw_color(200, 200, 200)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(6)

    # Body
    pdf.set_font("Helvetica", size=11)
    pdf.set_text_color(40, 40, 40)
    for para in body.split("\n"):
        if para.strip().startswith("##"):
            pdf.set_font("Helvetica", "B", 13)
            pdf.multi_cell(0, 8, _latin1_safe(para.replace("##", "").strip()))
            pdf.set_font("Helvetica", size=11)
        elif para.strip().startswith("#"):
            pdf.set_font("Helvetica", "B", 15)
            pdf.multi_cell(0, 9, _latin1_safe(para.replace("#", "").strip()))
            pdf.set_font("Helvetica", size=11)
        else:
            pdf.multi_cell(0, 7, _latin1_safe(para))
        pdf.ln(1)

    path = os.path.join(_OUTPUT_DIR, filename)
    pdf.output(path)
    return path


# ── DOCX ──────────────────────────────────────────────────────

def _make_docx(title: str, body: str, filename: str) -> str:
    from docx import Document
    from docx.shared import Pt, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH

    doc = Document()

    # Title
    h = doc.add_heading(title, level=0)
    h.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Date
    date_p = doc.add_paragraph(f"Generated by iZACH — {time.strftime('%d %b %Y, %H:%M')}")
    date_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    date_p.runs[0].font.color.rgb = RGBColor(120, 120, 120)
    date_p.runs[0].font.size = Pt(10)

    doc.add_paragraph()

    for para in body.split("\n"):
        if para.strip().startswith("## "):
            doc.add_heading(para[3:].strip(), level=2)
        elif para.strip().startswith("# "):
            doc.add_heading(para[2:].strip(), level=1)
        elif para.strip().startswith("- ") or para.strip().startswith("• "):
            p = doc.add_paragraph(para.strip()[2:], style="List Bullet")
        else:
            doc.add_paragraph(para)

    path = os.path.join(_OUTPUT_DIR, filename)
    doc.save(path)
    return path


# ── Auto-content builders ─────────────────────────────────────

def _build_activity_report() -> str:
    lines = ["# iZACH Activity Report\n"]
    try:
        import csv
        log = os.path.join(os.path.dirname(os.path.dirname(__file__)), "command_log.csv")
        if os.path.exists(log):
            with open(log, newline="", encoding="utf-8") as f:
                rows = list(csv.DictReader(f))
            today = time.strftime("%Y-%m-%d")
            today_rows = [r for r in rows if r.get("timestamp", "").startswith(today)]
            lines.append(f"## Today's Commands ({len(today_rows)} total)\n")
            for r in today_rows[-20:]:
                lines.append(f"- [{r.get('timestamp','')[:16]}] {r.get('command','')}")
        else:
            lines.append("No command log found.")
    except Exception as e:
        lines.append(f"Error reading log: {e}")
    return "\n".join(lines)


def _build_weekly_summary() -> str:
    return _build_activity_report()


# ── Public API ────────────────────────────────────────────────

def generate(
    content: str = "",
    fmt: str = "pdf",
    title: str = "iZACH Document",
    template: str = "custom",
) -> tuple[bool, str, str]:
    """
    Returns (ok, message, filepath).
    template: 'custom' | 'activity_report' | 'weekly_summary' | 'letter' | 'notes'
    fmt: 'pdf' | 'docx'
    """
    _ensure_dir()

    if template == "activity_report":
        content = _build_activity_report()
        title   = "Activity Report"
    elif template == "weekly_summary":
        content = _build_weekly_summary()
        title   = "Weekly Summary"
    elif template == "notes" and not content:
        content = "Your notes go here."
        title   = "Notes"

    if not content:
        return False, "No content provided.", ""

    ts  = _timestamp()
    fmt = fmt.lower()

    try:
        if fmt == "docx":
            fname = f"{template}_{ts}.docx"
            path  = _make_docx(title, content, fname)
        else:
            fname = f"{template}_{ts}.pdf"
            path  = _make_pdf(title, content, fname)

        # Notify via WS
        try:
            from modules.ws_bridge import broadcast
            broadcast({"type": "document_ready", "filename": fname,
                       "path": path, "ts": time.strftime("%H:%M")})
        except Exception:
            pass

        return True, f"Document ready: {fname}", path

    except ImportError as e:
        missing = "fpdf2" if "fpdf" in str(e) else "python-docx"
        return False, f"Missing library: pip install {missing}", ""
    except Exception as e:
        return False, f"Document generation failed: {e}", ""


def generate_async(content="", fmt="pdf", title="iZACH Document", template="custom",
                   speak_fn=None):
    def _run():
        ok, msg, _ = generate(content, fmt, title, template)
        if speak_fn:
            speak_fn(msg)
    threading.Thread(target=_run, daemon=True).start()
