"""
modules/obsidian_brain.py
iZACH → Obsidian integration.
Writes structured markdown insights into separate .md files.
"""

import os
from datetime import datetime

# ── CONFIG ────────────────────────────────────────────────────
# Obsidian vault path — derived relative to the project root (was previously
# a hardcoded Windows path, which meant this silently never worked on macOS).
# Override with the IZACH_VAULT_PATH env var if your vault lives elsewhere.
VAULT_PATH = os.environ.get(
    "IZACH_VAULT_PATH",
    os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "iZACH-Brain"),
)


FILES = {
    "profile":        "User Profile.md",
    "preferences":    "Behavior Preferences.md",
    "insights":       "Usage Insights.md",
    "weaknesses":     "System Weaknesses.md",
    "commands":       "Frequent Commands.md",
    "learned_facts":  "Learned Facts.md",
    "system_profile": "System Profile.md",
    "brain_index":    "iZACH Brain.md",
}
PEOPLE_DIR = "People"   # sub-folder inside vault for person notes


# ── CORE UTILITIES ────────────────────────────────────────────


def log_smart_insight(intent, command, response):
    content = f"""
## {datetime.now().strftime("%Y-%m-%d %H:%M")}

- Intent: {intent}
- Command: {command}
- Response: {response}

"""
    with open(_path("insights"), "a", encoding="utf-8") as f:
        f.write(content + "\n---\n")

def _path(key: str) -> str:
    os.makedirs(VAULT_PATH, exist_ok=True)
    return os.path.join(VAULT_PATH, FILES[key])


def _read(key: str) -> str:
    p = _path(key)
    if os.path.exists(p):
        with open(p, "r", encoding="utf-8") as f:
            return f.read()
    return ""


def _write(key: str, content: str):
    with open(_path(key), "w", encoding="utf-8") as f:
        f.write(content)


def _section_exists(content: str, section: str) -> bool:
    return f"## {section}" in content


def _append_to_section(content: str, section: str, entry: str) -> str:
    """Append entry under an existing section."""
    marker = f"## {section}"
    idx    = content.find(marker)
    if idx == -1:
        return content + f"\n## {section}\n{entry}\n"
    # Find next section or end of file
    next_sec = content.find("\n## ", idx + len(marker))
    insert_at = next_sec if next_sec != -1 else len(content)
    return content[:insert_at] + entry + "\n\n" + content[insert_at:]


def _is_duplicate(content: str, entry_text: str) -> bool:
    """Avoid storing the same insight twice."""
    return entry_text.strip().lower() in content.lower()


def _ts() -> str:
    return datetime.now().strftime("%Y-%m-%d %H:%M")


# ── PUBLIC API ────────────────────────────────────────────────

def save_user_profile(name: str, preferences: dict):
    """Write/update the user profile file."""
    content = f"""# iZACH — User Profile
*Last updated: {_ts()}*

## Identity
- **Name:** {name}

## Preferences
"""
    for k, v in preferences.items():
        content += f"- **{k}:** {v}\n"
    _write("profile", content)
    print("[OBSIDIAN] User profile saved.")


def log_preference(category: str, preference: str):
    """Append a learned preference under a category section."""
    content = _read("preferences")
    if not content:
        content = "# Behavior Preferences\n*Auto-generated by iZACH*\n"
    if _is_duplicate(content, preference):
        return
    entry   = f"- [{_ts()}] {preference}"
    content = _append_to_section(content, category, entry)
    _write("preferences", content)
    print(f"[OBSIDIAN] Preference logged: {preference}")


def log_weakness(issue: str, context: str = ""):
    """Log a recurring failure or system weakness."""
    content = _read("weaknesses")
    if not content:
        content = "# System Weakness Log\n*Tracked by iZACH*\n\n## Recurring Issues\n"
    if _is_duplicate(content, issue):
        return
    entry   = f"- [{_ts()}] **{issue}**" + (f" — {context}" if context else "")
    content = _append_to_section(content, "Recurring Issues", entry)
    _write("weaknesses", content)
    print(f"[OBSIDIAN] Weakness logged: {issue}")


def update_frequent_commands(command_counts: dict, top_n: int = 10):
    """Rewrite the frequent commands file with latest top N."""
    sorted_cmds = sorted(command_counts.items(), key=lambda x: x[1], reverse=True)[:top_n]
    content = f"# Frequent Commands\n*Updated: {_ts()}*\n\n## Top Commands\n"
    for i, (cmd, count) in enumerate(sorted_cmds, 1):
        content += f"{i}. `{cmd}` — {count}x\n"
    _write("commands", content)
    print("[OBSIDIAN] Frequent commands updated.")


def generate_insights(log_file: str = "command_log.csv"):
    """Read CSV log and write a usage insights summary."""
    import csv
    from collections import defaultdict

    if not os.path.exists(log_file):
        print("[OBSIDIAN] No log file found.")
        return

    with open(log_file, "r", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))

    if not rows:
        return

    total    = len(rows)
    success  = sum(1 for r in rows if r.get("status") == "success")
    times = []
    for r in rows:
        try:
            times.append(float(r.get("time_taken") or 0))
        except:
            pass
    avg_time = round(sum(times) / len(times), 3) if times else 0

    cmd_counts = defaultdict(int)
    for r in rows:
        c = r.get("command", "").strip()
        if c:
            cmd_counts[c] += 1
    most_used = max(cmd_counts, key=cmd_counts.get) if cmd_counts else "N/A"

    voice_total = sum(1 for r in rows if r.get("input_type") == "voice")
    text_total  = sum(1 for r in rows if r.get("input_type") == "text")

    entry = f"""
### Session — {_ts()}
- Total commands: **{total}**
- Success rate: **{round(success/total*100,1)}%**
- Avg response time: **{avg_time}s**
- Most used command: **{most_used}**
- Voice commands: {voice_total} | Text commands: {text_total}
"""
    content = _read("insights")
    if not content:
        content = "# Usage Insights\n*Auto-generated by iZACH*\n\n## Sessions\n"
    content = _append_to_section(content, "Sessions", entry)
    _write("insights", content)

    # Also update frequent commands
    update_frequent_commands(cmd_counts)
    print("[OBSIDIAN] Insights generated.")


def log_learned_fact(key: str, category: str, question: str, answer: str):
    """
    Save an answer from the curiosity engine into Learned Facts.md.
    Each entry is linked back to [[iZACH Brain]] for graph connectivity.
    """
    content = _read("learned_facts")
    if not content:
        content = (
            "# Learned Facts\n"
            "*Answers iZACH collected by asking [[iZACH Brain|the user]] directly.*\n\n"
        )

    entry = (
        f"\n### {category} — `{key}`\n"
        f"**Asked:** {_ts()}\n"
        f"**Q:** {question}\n"
        f"**A:** {answer}\n"
        f"*Tags: #{category.lower()} #learned*\n"
    )

    if _is_duplicate(content, answer.strip()):
        # Update existing answer instead of duplicating
        return

    content += entry
    _write("learned_facts", content)
    _update_brain_index()
    print(f"[OBSIDIAN] Learned fact saved: {key}")


def save_system_profile(summary: str, raw_apps: str = "", raw_events: str = ""):
    """
    Write system log analysis to System Profile.md.
    Linked to [[iZACH Brain]] for graph connectivity.
    """
    top_apps = [line.strip() for line in raw_apps.splitlines() if line.strip()][:30]
    apps_section = "\n".join(f"- `{a}`" for a in top_apps) if top_apps else "_No data_"

    content = (
        f"# System Profile\n"
        f"*Last analyzed: {_ts()} — part of [[iZACH Brain]]*\n\n"
        f"## Analysis\n"
        f"{summary}\n\n"
        f"## Recently Used Apps (last 10 days)\n"
        f"{apps_section}\n\n"
        f"## Linked Notes\n"
        f"- [[User Profile]]\n"
        f"- [[Behavior Preferences]]\n"
        f"- [[Usage Insights]]\n"
    )
    _write("system_profile", content)
    _update_brain_index()
    print("[OBSIDIAN] System profile saved.")


def save_person_profile(name: str, facts: dict):
    """
    Write/update a person note at iZACH-Brain/People/{Name}.md.
    Each note links back to [[iZACH Brain]] for graph connectivity.
    Merges new facts with existing content — never overwrites known data.
    """
    people_path = os.path.join(VAULT_PATH, PEOPLE_DIR)
    os.makedirs(people_path, exist_ok=True)
    note_path = os.path.join(people_path, f"{name}.md")

    # Read existing content to merge
    existing = {}
    if os.path.exists(note_path):
        with open(note_path, "r", encoding="utf-8") as f:
            for line in f:
                m = __import__("re").match(r"^\*\*(.+?):\*\*\s+(.+)$", line.strip())
                if m:
                    existing[m.group(1).lower().replace(" ", "_")] = m.group(2)

    merged = {**existing, **{k: v for k, v in facts.items() if v}}

    label_map = {
        "relation":    "Relationship",
        "works_at":    "Works at",
        "studies_at":  "Studies at",
        "notes":       "Notes",
        "whatsapp_number": "WhatsApp",
        "last_topic":  "Last topic",
        "birthday":    "Birthday",
    }

    facts_md = ""
    for k, v in merged.items():
        label = label_map.get(k, k.replace("_", " ").title())
        facts_md += f"**{label}:** {v}\n"

    content = (
        f"# {name}\n"
        f"*Last updated: {_ts()} — part of [[iZACH Brain]] → [[Relationships]]*\n\n"
        f"## Profile\n"
        f"{facts_md}\n"
        f"## Notes\n"
        f"_iZACH learns more about {name} over time through conversation and WhatsApp context._\n"
    )
    with open(note_path, "w", encoding="utf-8") as f:
        f.write(content)

    # Update/create Relationships index note
    _update_relationships_index(people_path)
    print(f"[OBSIDIAN] Person profile saved: {name}")


def _update_relationships_index(people_path: str):
    """Maintain People/Relationships.md — index of all known people."""
    people = []
    if os.path.isdir(people_path):
        for fname in os.listdir(people_path):
            if fname.endswith(".md") and fname != "Relationships.md":
                people.append(fname[:-3])

    links = "\n".join(f"- [[{p}]]" for p in sorted(people))
    content = (
        f"# Relationships\n"
        f"*Part of [[iZACH Brain]] — updated {_ts()}*\n\n"
        f"People iZACH knows about:\n\n"
        f"{links}\n"
    )
    with open(os.path.join(people_path, "Relationships.md"), "w", encoding="utf-8") as f:
        f.write(content)


def _update_brain_index():
    """
    Maintain iZACH Brain.md — a central hub note with [[wikilinks]] to all
    other notes. Call after any write so the graph stays connected.
    """
    note_links = {
        "profile":        ("User Profile",        "Who the user is — name, role, preferences."),
        "preferences":    ("Behavior Preferences", "Learned behavioral patterns and preferences."),
        "learned_facts":  ("Learned Facts",        "Answers iZACH collected by asking the user."),
        "system_profile": ("System Profile",       "10-day Windows system usage and health analysis."),
        "insights":       ("Usage Insights",       "Command usage stats and session summaries."),
        "weaknesses":     ("System Weaknesses",    "Recurring failures and problem areas."),
        "commands":       ("Frequent Commands",    "Top commands by usage frequency."),
    }
    # Check People folder separately
    people_dir = os.path.join(VAULT_PATH, PEOPLE_DIR)
    people_count = len([f for f in os.listdir(people_dir) if f.endswith(".md") and f != "Relationships.md"]) if os.path.isdir(people_dir) else 0
    people_status = f"✓ ({people_count} people)" if people_count else "○"

    links_md = ""
    for key, (title, desc) in note_links.items():
        exists = os.path.exists(_path(key))
        status = "✓" if exists else "○"
        links_md += f"- {status} [[{title}]] — {desc}\n"
    links_md += f"- {people_status} [[Relationships]] — People iZACH knows about.\n"

    content = (
        f"# iZACH Brain\n"
        f"*Central knowledge graph — updated {_ts()}*\n\n"
        f"> This is iZACH's memory hub. All notes link back here.\n\n"
        f"## Knowledge Nodes\n"
        f"{links_md}\n"
        f"## About\n"
        f"iZACH builds this graph automatically — through observation, conversation, "
        f"and system analysis. Each node stores a different type of memory.\n"
    )
    _write("brain_index", content)
    print("[OBSIDIAN] Brain index updated.")