"""
modules/obsidian_brain.py
iZACH → Obsidian integration.
Writes structured markdown insights into separate .md files.
"""

import os
from datetime import datetime
from collections import defaultdict

# ── CONFIG ────────────────────────────────────────────────────
# Set this to your Obsidian vault path
VAULT_PATH = r"C:\Projects\iZACH\iZACH-Brain"


FILES = {
    "profile":     "User Profile.md",
    "preferences": "Behavior Preferences.md",
    "insights":    "Usage Insights.md",
    "weaknesses":  "System Weaknesses.md",
    "commands":    "Frequent Commands.md",
}


# ── CORE UTILITIES ────────────────────────────────────────────


def log_smart_insight(intent, command, response):
    content = f"""
## {datetime.now().strftime("%Y-%m-%d %H:%M")}

- Intent: {intent}
- Command: {command}
- Response: {response}

"""
    with open(_path("insights"), "a", encoding="utf-8") as f:
        f.write(content + "\n---\n")

def _path(key: str) -> str:
    os.makedirs(VAULT_PATH, exist_ok=True)
    return os.path.join(VAULT_PATH, FILES[key])


def _read(key: str) -> str:
    p = _path(key)
    if os.path.exists(p):
        with open(p, "r", encoding="utf-8") as f:
            return f.read()
    return ""


def _write(key: str, content: str):
    with open(_path(key), "w", encoding="utf-8") as f:
        f.write(content)


def _section_exists(content: str, section: str) -> bool:
    return f"## {section}" in content


def _append_to_section(content: str, section: str, entry: str) -> str:
    """Append entry under an existing section."""
    marker = f"## {section}"
    idx    = content.find(marker)
    if idx == -1:
        return content + f"\n## {section}\n{entry}\n"
    # Find next section or end of file
    next_sec = content.find("\n## ", idx + len(marker))
    insert_at = next_sec if next_sec != -1 else len(content)
    return content[:insert_at] + entry + "\n\n" + content[insert_at:]


def _is_duplicate(content: str, entry_text: str) -> bool:
    """Avoid storing the same insight twice."""
    return entry_text.strip().lower() in content.lower()


def _ts() -> str:
    return datetime.now().strftime("%Y-%m-%d %H:%M")


# ── PUBLIC API ────────────────────────────────────────────────

def save_user_profile(name: str, preferences: dict):
    """Write/update the user profile file."""
    content = f"""# iZACH — User Profile
*Last updated: {_ts()}*

## Identity
- **Name:** {name}

## Preferences
"""
    for k, v in preferences.items():
        content += f"- **{k}:** {v}\n"
    _write("profile", content)
    print("[OBSIDIAN] User profile saved.")


def log_preference(category: str, preference: str):
    """Append a learned preference under a category section."""
    content = _read("preferences")
    if not content:
        content = "# Behavior Preferences\n*Auto-generated by iZACH*\n"
    if _is_duplicate(content, preference):
        return
    entry   = f"- [{_ts()}] {preference}"
    content = _append_to_section(content, category, entry)
    _write("preferences", content)
    print(f"[OBSIDIAN] Preference logged: {preference}")


def log_weakness(issue: str, context: str = ""):
    """Log a recurring failure or system weakness."""
    content = _read("weaknesses")
    if not content:
        content = "# System Weakness Log\n*Tracked by iZACH*\n\n## Recurring Issues\n"
    if _is_duplicate(content, issue):
        return
    entry   = f"- [{_ts()}] **{issue}**" + (f" — {context}" if context else "")
    content = _append_to_section(content, "Recurring Issues", entry)
    _write("weaknesses", content)
    print(f"[OBSIDIAN] Weakness logged: {issue}")


def update_frequent_commands(command_counts: dict, top_n: int = 10):
    """Rewrite the frequent commands file with latest top N."""
    sorted_cmds = sorted(command_counts.items(), key=lambda x: x[1], reverse=True)[:top_n]
    content = f"# Frequent Commands\n*Updated: {_ts()}*\n\n## Top Commands\n"
    for i, (cmd, count) in enumerate(sorted_cmds, 1):
        content += f"{i}. `{cmd}` — {count}x\n"
    _write("commands", content)
    print("[OBSIDIAN] Frequent commands updated.")


def generate_insights(log_file: str = "command_log.csv"):
    """Read CSV log and write a usage insights summary."""
    import csv
    from collections import defaultdict

    if not os.path.exists(log_file):
        print("[OBSIDIAN] No log file found.")
        return

    with open(log_file, "r", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))

    if not rows:
        return

    total    = len(rows)
    success  = sum(1 for r in rows if r.get("status") == "success")
    times = []
    for r in rows:
        try:
            times.append(float(r.get("time_taken") or 0))
        except:
            pass
    avg_time = round(sum(times) / len(times), 3) if times else 0

    cmd_counts = defaultdict(int)
    for r in rows:
        c = r.get("command", "").strip()
        if c:
            cmd_counts[c] += 1
    most_used = max(cmd_counts, key=cmd_counts.get) if cmd_counts else "N/A"

    voice_total = sum(1 for r in rows if r.get("input_type") == "voice")
    text_total  = sum(1 for r in rows if r.get("input_type") == "text")

    entry = f"""
### Session — {_ts()}
- Total commands: **{total}**
- Success rate: **{round(success/total*100,1)}%**
- Avg response time: **{avg_time}s**
- Most used command: **{most_used}**
- Voice commands: {voice_total} | Text commands: {text_total}
"""
    content = _read("insights")
    if not content:
        content = "# Usage Insights\n*Auto-generated by iZACH*\n\n## Sessions\n"
    content = _append_to_section(content, "Sessions", entry)
    _write("insights", content)

    # Also update frequent commands
    update_frequent_commands(cmd_counts)
    print("[OBSIDIAN] Insights generated.")